---
title: Disk Benchmarks - save image
output: html_document
---

## Simulate the user's environment

Data set creation

```{r read_config}
source("config.R")
source("globals.R")
```

```{r create_data}
create_data(use_large_data)
```

How big is each dataframe in memory?

```{r df_sizes}
object.size(df1) / 1e6
lobstr::obj_size(df1) / 1e6
```

## Simulated RSP/RSW session suspend

Simulate the RSP/RSW session suspend with the `save.image()` function.

### Disk 1

```{r disk_1_write}
if(!dir.exists(disk_1_path)){
  dir.create(disk_1_path, recursive = TRUE)
}

filename <- paste0(disk_1_path, "/test-image.RData")

if (file.exists(filename)){
  unlink(filename)
}
Sys.time()
system.time(save.image(filename, compress = FALSE))
Sys.time()
round(file.size(filename)/(1024*1024*1024), 1) # to get bytes to GBytes
```


### Disk 2

```{r disk_2_write}
if(!dir.exists(disk_2_path)){
  dir.create(disk_2_path, recursive = TRUE)
}

filename <- paste0(disk_2_path, "/test-image.RData")

if (file.exists(filename)){
  unlink(filename)
}
Sys.time()
system.time(save.image(filename, compress = FALSE))
Sys.time()
round(file.size(filename)/(1024*1024*1024), 1) # to get bytes to GBytes
```

## Simulated RSP/RSW session resume

### Disk 1

```{r disk_1_restore}
# empty the workspace
rm(list = ls())

# Read the config again
source("config.R")
source("globals.R")

if(!dir.exists(disk_1_path)){
  dir.create(disk_1_path, recursive = TRUE)
}

filename <- paste0(disk_1_path, "/test-image.RData")
Sys.time()
system.time(load(filename))
Sys.time()
```

Check that objects have loaded

```{r efs_check}
object.size(df1) / 1e6
ls()
unlink(filename)
```

### Disk 2

```{r disk_2_restore}
rm(list = ls())

# Read the config again
source("config.R")
source("globals.R")

if(!dir.exists(disk_2_path)){
  dir.create(disk_2_path, recursive = TRUE)
}

filename <- paste0(disk_2_path, "/test-image.RData")

Sys.time()
system.time(load(filename))
Sys.time()
```

Check that objects have loaded

```{r ebs_check}
object.size(df1) / 1e6
ls()
unlink(filename)
```
