---
title: Disk Benchmarks - save image compressed
output: html_document
---

## Simulate the user's environment

Data set creation function

```{r make_df}
make_df <- function(nrow, ncol) {
  cbind(
    as.data.frame(matrix(
      runif(nrow * ncol), nrow = nrow, ncol = ncol
    )),
    rep(
      'THIS IS A VERY LONG TEXT STRING TO TEST A THEORY ABOUT THE STRING CACHE THIS IS A VERY LONG TEXT STRING TO TEST A THEORY ABOUT THE STRING CACHE',
      nrow
    ),
    rep(
      'THIS IS A DIFFERENT VERY LONG TEXT STRING TO TEST A THEORY ABOUT THE STRING CACHE THIS IS A VERY LONG TEXT STRING TO TEST A THEORY ABOUT THE STRING CACHE',
      nrow
    )
    
  )
  
}
```


Figure out how much data to create

```{r calc_rows}
# This will give us a data set of about 103G when saved
rows_needed <- round(500 * 1024 * 1024 / (8001904 / 100000) * 2.5)
```

Create the data

```{r create_data}
local({
  df <- make_df(nrow = rows_needed, ncol = 3)
  
  for (i in 1:20) {
    assign(paste0("df", i), df, envir = .GlobalEnv)
  }
})
```

How big is each dataframe in memory?

```{r df_size}
object.size(df1) / 1e6
lobstr::obj_size(df1) / 1e6
```

## Session save using compression

### EFS

```{r efs_save_compressed}
filename <- "/home/efs-mount/mark/efs_image_compressed.RData"
if (file.exists(filename)){
  unlink(filename)
}
Sys.time()
system.time(save.image(filename, compress = TRUE))
Sys.time()
round(file.size(filename)/(1024*1024*1024), 1) # to get bytes to GBytes
```


### EBS

```{r ebs_save_compressed}
filename <- "/ebs-local/ebs_image_compressed.RData"
if (file.exists(filename)){
  unlink(filename)
}
Sys.time()
system.time(save.image(filename, compress = TRUE))
Sys.time()
round(file.size(filename)/(1024*1024*1024), 1) # to get bytes to GBytes
```


## Session restore using compression

## Simulated RSP/RSW session resume

### EFS

```{r efs_restore_compressed}
rm(list = ls())
filename <- "/home/efs-mount/mark/efs_image_compressed.RData"
Sys.time()
system.time(load(filename))
Sys.time()
```

Check that everything has loaded properly

```{r efs_check}
lobstr::obj_size(df1) / 1e6
ls()
unlink(filename)
```

### EBS

```{r ebs_restore_compressed}
rm(list = ls())
filename <- "/ebs-local/ebs_image_compressed.RData"
Sys.time()
system.time(load(filename))
Sys.time()
```

Check that everything has loaded properly

```{r ebs_check}
lobstr::obj_size(df1) / 1e6
ls()
unlink(filename)
```


